FROM node:20-alpine AS build
WORKDIR /app
RUN npm install -g pnpm@8.15.5
COPY pnpm-workspace.yaml package.json tsconfig.base.json ./
COPY apps/server/package.json apps/server/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN pnpm install --filter @p42/web... --filter @p42/shared...
COPY . .
RUN pnpm --filter @p42/shared build
RUN pnpm --filter @p42/web build

FROM nginx:1.29.3-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
EXPOSE 80
